
package com.restjob.controller.providers.AppSpider.ws;

import com.restjob.controller.Config;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The user has to pass valid credentials.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.3-hudson-757-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NTOService", targetNamespace = "http://ntobjectives.com/webservices/", wsdlLocation = "http://appspider.example.com/AppSpiderEntScanEngine/default.asmx?WSDL")
public class NTOService
    extends Service
{

    private final static URL NTOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.restjob.controller.providers.AppSpider.ws.NTOService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.restjob.controller.providers.AppSpider.ws.NTOService.class.getResource(".");
            url = new URL(baseUrl, "http://appspider.example.com/AppSpiderEntScanEngine/default.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://appspider.example.com/AppSpiderEntScanEngine/default.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NTOSERVICE_WSDL_LOCATION = url;
    }

    public NTOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NTOService() {
        super(NTOSERVICE_WSDL_LOCATION, new QName("http://ntobjectives.com/webservices/", "NTOService"));
    }

    /**
     * 
     * @return
     *     returns NTOServiceSoap
     */
    @WebEndpoint(name = "NTOServiceSoap")
    public NTOServiceSoap getNTOServiceSoap() {
        return super.getPort(new QName("http://ntobjectives.com/webservices/", "NTOServiceSoap"), NTOServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NTOServiceSoap
     */
    @WebEndpoint(name = "NTOServiceSoap")
    public NTOServiceSoap getNTOServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ntobjectives.com/webservices/", "NTOServiceSoap"), NTOServiceSoap.class, features);
    }

}
